name: Daily Summary Bot

on:
  schedule:
    # Se ejecuta todos los días a las 13:00 UTC (07:00 AM hora CDMX)
    - cron: '0 13 * * *'
  workflow_dispatch: # Para que tú lo dispares cuando quieras probar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests yfinance python-telegram-bot python-dotenv

      - name: Ejecutar el Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
          ACCIONES_CONFIG: ${{ secrets.ACCIONES_CONFIG }}
          LOL_API_KEY: ${{ secrets.LOL_API_KEY }}
        run: python telegram_bot.py
